name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - '/'
        - '-'
        - '+'
        - '*'
      name:
        description: enter first number
        #input has to be provide for the workflow to run
        required: true
        

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Calculator
        run: | 
          echo "select the operator you want to choose for doing your operations with 22 and 7" 
          echo "as you have selected ${{ inputs.choice }} than the output is"
          22${{ inputs.choice }}7
          echo "Hello ${{github.event.inputs.name}}"
