name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - '/'
        - '-'
        - '+'
        - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Calculator
        run: | 
          print "choice is ${{ inputs.choice }}" / ${{ inputs.choice }}
          print(2+4)
        shell: python
