name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - '/'
        - '-'
        - '+'
        - '*'
      title:
      type: input.text
      label: Title
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Calculator
        run: | 
          2${{ inputs.choice }}4
