name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - '/'
        - '-'
        - '+'
        - '*'
      number1:
        description: enter first number
        #input has to be provide for the workflow to run
        required: true
      number2:
        description: enter second number
        #input has to be provide for the workflow to run
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Calculator
        run: | 
          ${{github.event.inputs.number1}}${{ inputs.choice }}${{github.event.inputs.number2}}

